### ISSUE TITLE
Mass upload files to be plotted on Graph Render Plugin (Child Type)

### ISSUE THREAD

**Issue by barbaralafuente** [OpenDataRepository/data-publisher#133]
Be able to mass upload plot files in a Graph Render Plugin Child Type.

**Comment by ajpires** [comment]
From a programming standpoint, there are two parts to this request...the first part is basically "upload multiple files"...that was mentioned way back in issue #53 and taken care of as a result of commit a106129.  The second part is effectively "CSV Import needs to work for child/linked Datatypes"...this part was technically brought up in issue #126.

The underlying request is still pretty high priority (second or third highest at the time of this comment, I believe), but since both parts of this request have been brought up previously...closing this issue makes sense from the perspective of managing issues on github.
