### ISSUE TITLE
Datafield history display

### ISSUE THREAD

**Issue by ajpires** [OpenDataRepository/data-publisher#23]
Reverting back to an older value stored in the datafield doesn't update the value displayed on screen, requiring a refresh of the page to see the reverted value

**Comment by barbaralafuente** [comment]
Sometimes the View Field History table takes too much time to show up or even it doesn´t show up.

**Comment by ajpires** [comment]
Both of these issues should be fixed as a result of commit 50f9a56

**Comment by ajpires** [comment]
The speed issue could be due to the namespacing for our entities taking up at least  24 characters...meaning that the 18 character database key attached to the ext_log_entries.object_class field would be pretty much useless...

In addition, I apparently never wrote what was required to get Datafield history of Radio Field types.

**Comment by natestone** [comment]
So, to this issue, we need to switch to using soft-delete for all updates.  Instead of updating the field and logging it, we need to soft-delete the existing field instance and create a new field instance with the changed value.

Then, we will get the complete field history right in the existing value table.  This does create additional table searching overhead, but is probably worthwhile since we can show the state of the record at an point in time by choosing a query that uses the deletedAt field to pull changes made before a certain date.

**Comment by ajpires** [comment]
Fixed as a result of soft-deleteable changes made during branch 1.5.1
