### ISSUE TITLE
Upload TIF files

### ISSUE THREAD

**Issue by barbaralafuente** [OpenDataRepository/data-publisher#85]
Need of the ability to upload .TIF files

**Comment by natestone** [comment]
This is a tricky issue.  I'm not a fan of using Java within web browsers.  I have found a javascript plugin that supposedly will display TIF files, but it has not been updated in 2+ years.

Java is poorly supported within web browsers due to security issues.  I'll do some investigation and see what the best solution is.

**Comment by blafuentevalverde** [comment]
outdated
