### ISSUE TITLE
Markdown field margins (or padding?)

### ISSUE THREAD

**Issue by barbaralafuente** [OpenDataRepository/data-publisher#87]
Reduce the space on top and under the markdown field.

**Comment by natestone** [comment]
I'll take care of it.

**Comment by ajpires** [comment]
If memory serves, this was brought up due to the markdown fields in chemin...it's apparently caused by using raw html code instead of the expected syntax for the markdown field.  Need to locate a decent cheat-sheet and add a link to it on the slideout when modifying the contents of a markdown field...
